# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Run tests

on:
  push:
    branches: [ master, v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vs-version: [latest, 51, 47]
        python-version: ["3.11"]


    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and Compile VapourSynth
      env:
        REQUESTED_VS_VERSION: ${{ matrix.vs-version }}
      run: |
        npm install
        npm run compile
    - name: Attempt using VapourSynth
      run: |
        python -c "import vapoursynth; vapoursynth.core.version_number()"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tools
        path: /tmp/artifacts
